apiVersion: v1
data:
  promtail.yml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push

    scrape_configs:
      - job_name: "__service__name__"
        pipeline_stages:
          - json:
              expressions:
                level: level
                message: message
                timestamp: timestamp
                service: service
                meta:
          - labels:
              level:
          - timestamp:
              source: timestamp
              format: RFC3339Nano
        static_configs:
          - targets:
              - localhost
            labels:
              job: "__service_name__"
              instance: "__instance_name__"
              env: "production"
              __path__: /var/log/app.log
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: promtail
  name: promtail-cm1
