apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodata
  namespace: myapp
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: myapp-local-storage
  resources:
    requests:
      storage: 500Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafanadata
  namespace: myapp
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: myapp-local-storage
  resources:
    requests:
      storage: 500Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs
  namespace: myapp
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: myapp-local-storage
  resources:
    requests:
      storage: 500Mi
