apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodata
  namespace: myapp
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafanadata
  namespace: myapp
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs
  namespace: myapp
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

